import { ConfigService, HttpService, MessagingService, Players, RunService, TeleportService } from "@rbxts/services";
import { HostedService } from "engine/shared/di/HostedService";
import { Element } from "engine/shared/Element";
import { JSON } from "engine/shared/fixes/Json";
import { PlayerRank } from "engine/shared/PlayerRank";
import { t } from "engine/shared/t";
import { isNotAdmin_AutoBanned } from "server/BanAdminExploiter";
import { CustomRemotes } from "shared/Remotes";
import type { AnnouncementController } from "server/AnnouncementController";
import type { PlayerDatabase } from "server/database/PlayerDatabase";
import type { ServerPlayersController } from "server/ServerPlayersController";
import type { ServerRosterEntry } from "shared/Remotes";

let botToken: string | undefined;
let botTokenResolved = false;

const getBotToken = (): string | undefined => {
	if (botTokenResolved) return botToken;
	botTokenResolved = true;

	const [ok, value] = pcall(() => ConfigService.GetConfigAsync().GetValue("BOTTOKEN") as string | undefined);
	if (!ok) return undefined;

	botToken = value === "" ? undefined : value; // "" is truthy in Luau
	return botToken;
};

const ROSTER_TOPIC = "SERVERS"; // Servers announce themselves to each other to generate a roster
const COMMAND_TOPIC = "COMMAND"; // Commands come in from this channel (OpenCloud API + Game UI)
const BOT_URL = "https://bot.ftrookie.com"; // docs/GAME_INTEGRATION.md

const ANNOUNCE_INTERVAL = 45;
const ROSTER_TTL = ANNOUNCE_INTERVAL * 3; // Three missed announces before a peer is presumed gone
const ANNOUNCE_DEBOUNCE = 1; // Announce self only once per peer discovery
const POLL_INTERVAL = 30; // Backup if MessagingService can't subscribe, late execution beats never
const MAX_HANDLED = 200; // Max size of the Command ID dedupe array

/**
 * Response code to a command the server received
 ** Success -> Successfully executed on this server
 ** Refused -> A condition was not met and the command could not be executed, includes Partial success
 ** Fail -> An argument was invalid or an unexpected error occured
 ** Nothing -> This server decided to not take action, or has already executed this command
 ** Unsupported -> This server does not understand the command, usually parity mismatch
 */
type Outcome = "Success" | "Refused" | "Fail" | "Nothing" | "Unsupported";
type CommandResult = { readonly outcome: Outcome; readonly response?: string };

type ServerKind = "public" | "private" | "reserved";
/** Acknowledgement body POSTed to the bot; mirrored in docs/GAME_INTEGRATION.md. */
type CommandAck = {
	readonly jobId: string;
	readonly outcome: Outcome;
	readonly response?: string;
	readonly kind: ServerKind;
	readonly roster: readonly string[];
};

type CommandEnvelope = {
	readonly id: string; // uuid generated by the bot
	readonly name: string; // command id
	readonly issuedAt: number;
	readonly args?: { readonly [k in string]: unknown };
	readonly targetJobId?: string; // Command ignored unless this is the target server
};

// Command args arrive as untrusted JSON, so each handler's shape is validated rather than annotated.
const restartArgs = t.interface({
	text: t.string.orUndefined(),
	ttl: t.number.orUndefined(),
});
const announceArgs = t.interface({
	text: t.string,
	display: t.union(t.const("chat"), t.const("popup"), t.const("both")).orUndefined(),
	ttl: t.number.orUndefined(),
});
const kickArgs = t.interface({
	userId: t.number,
	reason: t.string.orUndefined(),
});
const grantArgs = t.interface({
	userId: t.number,
	blockId: t.string,
	// absent removes the override entirely rather than setting 0, so a revoked block leaves no key behind
	limit: t.number.orUndefined(),
});

/** Runs `run` only once the args match `vtype`, failing the command with the validator's own message. */
const withArgs =
	<T>(vtype: t.Type<T>, run: (args: T) => CommandResult) =>
	(args: CommandEnvelope["args"]): CommandResult => {
		const values = args ?? {};
		const result = t.newResult();
		if (!t.typeCheck(values, vtype, result)) return { outcome: "Fail", response: result.toString() };

		return run(values);
	};

const serverType = (): ServerKind => {
	if (game.PrivateServerId === "") return "public";
	return game.PrivateServerOwnerId !== 0 ? "private" : "reserved";
};

@injectable
export class CommandController extends HostedService {
	/** `jobId` to `time` map, received stamped so no clock desync */
	private readonly roster = new Map<string, number>();
	/** Stores acknowledgements per command uuid in case of a command re-issue */
	private readonly handled = new Map<string, CommandResult>();
	/** handled Map has no First-In First-Out (Queue) */
	private readonly handledOrder: string[] = [];
	private readonly handlers: { readonly [name in string]: (args: CommandEnvelope["args"]) => CommandResult };

	private commandsAlive = false;
	private announceQueued = false;
	private seeded = false;
	private watermark = 0;

	constructor(
		@inject announcements: AnnouncementController,
		@inject playersController: ServerPlayersController,
		@inject database: PlayerDatabase,
		@inject blockList: BlockList,
	) {
		super();

		this.handlers = {
			restart: withArgs(restartArgs, (args) => {
				const ttl = args.ttl ?? 60;
				const text = args.text ?? "A new update is live!";

				announcements.announceRestart(text, ttl);
				if (ttl > 10) {
					task.delay(ttl - 10, () => announcements.chat("Restart imminent — wrap up now!"));
				}
				task.delay(math.max(0, ttl - 10), () => playersController.autosaveAll());
				return { outcome: "Success", response: `Warned ${Players.GetPlayers().size()} player(s)` };
			}),

			announce: withArgs(announceArgs, (args) => {
				if (args.text.size() === 0) return { outcome: "Fail", response: "missing text" };

				announcements.announce(args.text, args.display ?? "both", args.ttl);
				return { outcome: "Success", response: `Shown to ${Players.GetPlayers().size()} player(s)` };
			}),

			ping: () => ({ outcome: "Success", response: `${Players.GetPlayers().size()} player(s)` }),

			players: () => ({
				outcome: "Success",
				response: Players.GetPlayers()
					.map((p) => p.Name)
					.join(", "),
			}),

			kick: withArgs(kickArgs, (args) => {
				const player = Players.GetPlayerByUserId(args.userId);
				if (player === undefined) return { outcome: "Nothing" };

				if (PlayerRank.isDevById(args.userId) || PlayerRank.isModById(args.userId)) {
					return { outcome: "Refused", response: "staff" };
				}

				player.Kick(`Reason: ${args.reason ?? "No reason was given"}`);
				return { outcome: "Success", response: `Kicked ${player.Name}` };
			}),

			// fixme: the bot targets an arbitrary server, so a grant issued while the player is online on a
			// different one is written from a row loaded before it, and that server's save on disconnect wipes
			// it. Temporary — the write belongs upstream of the servers rather than in whichever was picked.
			grant: withArgs(grantArgs, (args) => {
				if (!blockList.blocks[args.blockId as BlockId]) {
					return { outcome: "Fail", response: `Unknown block id ${args.blockId}` };
				}

				if (!database.setBlockLimit(args.userId, args.blockId, args.limit)) {
					return { outcome: "Fail", response: `Could not load ${args.userId}'s data; writes are refused` };
				}

				return {
					outcome: "Success",
					response:
						args.limit === undefined
							? `Removed ${args.blockId} from ${args.userId}`
							: `Granted ${args.limit}x ${args.blockId} to ${args.userId}`,
				};
			}),
		};

		// Not a `handlers` entry: those are reachable from the bot channel, which has no invoker to teleport.
		// Registered above the Studio guard so the remote is never silently dead on a Studio session.
		this.event.subscribeRegistration(() =>
			CustomRemotes.admin.adminJoinServer.subscribe((invoker, jobId): Response => {
				if (isNotAdmin_AutoBanned(invoker, "adm_join_server"))
					return { success: false, message: "Not an admin" };
				return this.joinServer(invoker, jobId);
			}),
		);
		this.event.subscribeRegistration(() =>
			CustomRemotes.admin.adminServerList.subscribe(
				(invoker): Response<{ readonly servers: readonly ServerRosterEntry[] }> => {
					if (isNotAdmin_AutoBanned(invoker, "adm_server_list")) {
						return { success: false, message: "Not an admin" };
					}

					return { success: true, servers: this.liveRosterEntries() };
				},
			),
		);

		if (RunService.IsStudio()) return;

		task.spawn(() => this.subscribeCommands());
		task.spawn(() => this.subscribeRoster());

		this.event.loop(ANNOUNCE_INTERVAL, () => this.announceSelf());
		this.event.loop(POLL_INTERVAL, () => this.poll());
	}

	private subscribeCommands() {
		for (let attempt = 1; ; attempt++) {
			const [ok, err] = pcall(() =>
				MessagingService.SubscribeAsync(COMMAND_TOPIC, (message) => {
					const raw = (message as { readonly Data: unknown }).Data;
					if (!typeIs(raw, "string")) return;

					const [decodeOk, command] = pcall(() => JSON.deserialize<CommandEnvelope>(raw));
					if (!decodeOk || command === undefined) return;

					this.execute(command);
				}),
			);
			if (ok) {
				this.commandsAlive = true;
				this.announceSelf();
				return;
			}

			$warn(`[CommandController] ${COMMAND_TOPIC} SubscribeAsync failed (attempt ${attempt}): ${err}`);
			task.wait(math.min(60, attempt * 5));
		}
	}

	private subscribeRoster() {
		const [ok, err] = pcall(() =>
			MessagingService.SubscribeAsync(ROSTER_TOPIC, (message) => {
				const jobId = (message as { readonly Data: unknown }).Data;
				if (!typeIs(jobId, "string") || jobId === game.JobId) return;

				const isNew = !this.roster.has(jobId);
				this.roster.set(jobId, time());
				if (isNew) this.queueAnnounce();
			}),
		);
		if (!ok)
			$warn(
				`[CommandController] ${ROSTER_TOPIC} SubscribeAsync failed, this server will report an empty roster: ${err}`,
			);
	}

	private announceSelf() {
		if (!this.commandsAlive) return;
		// a peer announces itself with only its job id, so no server ever learns another's kind
		pcall(() => MessagingService.PublishAsync(ROSTER_TOPIC, game.JobId));
	}

	private queueAnnounce() {
		if (this.announceQueued) return;

		this.announceQueued = true;
		task.delay(ANNOUNCE_DEBOUNCE, () => {
			this.announceQueued = false;
			this.announceSelf();
		});
	}

	private joinServer(invoker: Player, jobId: string): Response {
		if (RunService.IsStudio()) return { success: false, message: "Teleports do not work in Studio" };
		if (!typeIs(jobId, "string") || jobId.size() === 0) return { success: false, message: "No job id given" };
		if (jobId === game.JobId) return { success: false, message: "You are already on that server" };

		const options = Element.create("TeleportOptions", { ServerInstanceId: jobId });
		const [ok, err] = pcall(() => TeleportService.TeleportAsync(game.PlaceId, [invoker], options));
		if (ok) return { success: true };

		return { success: false, message: `Could not join ${jobId}: ${err}` };
	}

	/** Drops peers that have gone quiet past the TTL and returns the survivors, this server first. */
	private liveRosterEntries(): ServerRosterEntry[] {
		const now = time();
		const alive: ServerRosterEntry[] = [{ jobId: game.JobId, secondsAgo: 0 }];

		for (const [jobId, lastSeen] of this.roster) {
			if (now - lastSeen > ROSTER_TTL) {
				this.roster.delete(jobId);
				continue;
			}

			// sent as an age: time() is each server's own uptime, so a raw lastSeen would mean nothing to the client
			alive.push({ jobId, secondsAgo: now - lastSeen });
		}

		return alive;
	}

	private liveRoster(): string[] {
		return this.liveRosterEntries().map((e) => e.jobId);
	}

	private execute(command: CommandEnvelope) {
		this.watermark = math.max(this.watermark, command.issuedAt);

		const previous = this.handled.get(command.id);
		if (previous !== undefined) {
			task.spawn(() => this.acknowledge(command.id, previous));
			return;
		}

		const result = this.outcomeFor(command);
		this.remember(command.id, result);
		task.spawn(() => this.acknowledge(command.id, result));
	}

	private outcomeFor(command: CommandEnvelope): CommandResult {
		if (command.targetJobId !== undefined && command.targetJobId !== game.JobId) {
			return { outcome: "Nothing" };
		}

		const handler = this.handlers[command.name];
		if (handler === undefined) return { outcome: "Unsupported" };

		return handler(command.args);
	}

	private remember(id: string, result: CommandResult) {
		this.handled.set(id, result);
		this.handledOrder.push(id);

		while (this.handledOrder.size() > MAX_HANDLED) {
			const oldest = this.handledOrder.remove(0);
			if (oldest !== undefined) this.handled.delete(oldest);
		}
	}

	private acknowledge(id: string, result: CommandResult) {
		const token = getBotToken();
		if (token === undefined) {
			$warn("[CommandController] No BOTTOKEN: commands run but are never acknowledged to the bot.");
			return;
		}

		const [ok, err] = pcall(() =>
			HttpService.RequestAsync({
				Url: `${BOT_URL}/ack/${id}`,
				Method: "POST",
				Headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
				Body: JSON.serialize({
					jobId: game.JobId,
					outcome: result.outcome,
					response: result.response,
					kind: serverType(),
					roster: this.liveRoster(),
				} satisfies CommandAck),
			}),
		);
		if (!ok) $warn(`Command acknowledgement failed: ${err}`);
	}

	private poll() {
		const token = getBotToken();
		if (token === undefined) return;

		const [ok, result] = pcall(() =>
			HttpService.RequestAsync({
				Url: `${BOT_URL}/commands?since=${this.watermark}`,
				Method: "GET",
				Headers: { Authorization: `Bearer ${token}` },
			}),
		);
		if (!ok) return;

		const response = result as RequestAsyncResponse;
		if (!response.Success) return;

		const [decodeOk, commands] = pcall(() => JSON.deserialize<CommandEnvelope[]>(response.Body));
		if (!decodeOk || commands === undefined) return;

		for (const command of commands) {
			if (this.seeded) {
				this.execute(command);
				continue;
			}

			this.watermark = math.max(this.watermark, command.issuedAt);
		}

		this.seeded = true;
	}
}
