import { ConfigService, HttpService, MessagingService, Players, RunService } from "@rbxts/services";
import { HostedService } from "engine/shared/di/HostedService";
import { JSON } from "engine/shared/fixes/Json";
import { PlayerRank } from "engine/shared/PlayerRank";
import type { AnnouncementController } from "server/AnnouncementController";
import type { ServerPlayersController } from "server/ServerPlayersController";
import type { AnnouncementDisplay } from "shared/Remotes";

const ROSTER_TOPIC = "SERVERS"; // Servers announce themselves to each other to generate a roster
const COMMAND_TOPIC = "COMMAND"; // Commands come in from this channel (OpenCloud API + Game UI)
const BOT_URL = "https://bot.ftrookie.com"; // docs/GAME_INTEGRATION.md

const ANNOUNCE_INTERVAL = 45;
const ROSTER_TTL = ANNOUNCE_INTERVAL * 3; // Three missed announces before a peer is presumed gone
const ANNOUNCE_DEBOUNCE = 1; // Announce self only once per peer discovery
const POLL_INTERVAL = 30; // Backup if MessagingService can't subscribe, late execution beats never
const MAX_HANDLED = 200; // Max size of the Command ID dedupe array

/**
 * Response code to a command the server received
 ** Success -> Successfully executed on this server
 ** Refused -> A condition was not met and the command could not be executed, includes Partial success
 ** Fail -> An argument was invalid or an unexpected error occured
 ** Nothing -> This server decided to not take action, or has already executed this command
 ** Unsupported -> This server does not understand the command, usually parity mismatch
 */
type Outcome = "Success" | "Refused" | "Fail" | "Nothing" | "Unsupported";
type CommandResult = { readonly outcome: Outcome; readonly response?: string };

type CommandEnvelope = {
	readonly id: string; // uuid generated by the bot
	readonly name: string; // command id
	readonly issuedAt: number;
	readonly args?: { readonly [k in string]: unknown };
	readonly targetJobId?: string; // Command ignored unless this is the target server
};

const serverType = (): "public" | "private" | "reserved" => {
	if (game.PrivateServerId === "") return "public";
	return game.PrivateServerOwnerId !== 0 ? "private" : "reserved";
};

let botToken: string | undefined;
let botTokenResolved = false;

const getBotToken = (): string | undefined => {
	if (botTokenResolved) return botToken;
	botTokenResolved = true;

	const [ok, value] = pcall(() => ConfigService.GetConfigAsync().GetValue("BOTTOKEN") as string | undefined);
	if (!ok) return undefined;

	botToken = value === "" ? undefined : value; // "" is truthy in Luau
	return botToken;
};

@injectable
export class CommandController extends HostedService {
	/** `jobId` to `time` map, received stamped so no clock desync */
	private readonly roster = new Map<string, number>();
	/** Stores acknowledgements per command uuid in case of a command re-issue */
	private readonly handled = new Map<string, CommandResult>();
	/** handled Map has no First-In First-Out (Queue) */
	private readonly handledOrder: string[] = [];
	private readonly handlers: { readonly [name in string]: (args: CommandEnvelope["args"]) => CommandResult };

	private commandsAlive = false;
	private announceQueued = false;
	private seeded = false;
	private watermark = 0;

	constructor(@inject announcements: AnnouncementController, @inject playersController: ServerPlayersController) {
		super();

		this.handlers = {
			restart: (args?: { text?: string; ttl?: number }) => {
				const ttl = typeIs(args?.ttl, "number") ? args.ttl : 60;
				const text = typeIs(args?.text, "string") ? args.text : "A new update is live!";

				announcements.announce(text, "both", ttl, true);
				if (ttl > 10) {
					task.delay(ttl - 10, () => announcements.chat("Restart imminent — wrap up now!"));
				}
				task.delay(math.max(0, ttl - 10), () => playersController.autosaveAll());
				return { outcome: "Success", response: `Warned ${Players.GetPlayers().size()} player(s)` };
			},

			announce: (args?: { text?: string; display?: string; ttl?: number }) => {
				const text = args?.text;
				if (!typeIs(text, "string") || text.size() === 0) return { outcome: "Fail", response: "missing text" };

				const display = args?.display;
				const shown: AnnouncementDisplay = display === "chat" || display === "popup" ? display : "both";
				const ttl = typeIs(args?.ttl, "number") ? args.ttl : undefined;

				announcements.announce(text, shown, ttl);
				return { outcome: "Success", response: `Shown to ${Players.GetPlayers().size()} player(s)` };
			},

			ping: () => ({ outcome: "Success", response: `${Players.GetPlayers().size()} player(s)` }),

			players: () => ({
				outcome: "Success",
				response: Players.GetPlayers()
					.map((p) => p.Name)
					.join(", "),
			}),

			kick: (args?: { userId?: number; reason?: string }) => {
				const userId = args?.userId;
				if (!typeIs(userId, "number")) return { outcome: "Fail", response: "missing userId" };

				const player = Players.GetPlayerByUserId(userId);
				if (player === undefined) return { outcome: "Nothing" };

				if (PlayerRank.isDevById(userId) || PlayerRank.isModById(userId)) {
					return { outcome: "Refused", response: "staff" };
				}

				const reason = typeIs(args?.reason, "string") ? args.reason : "No reason was given";
				player.Kick(`Reason: ${reason}`);
				return { outcome: "Success", response: `Kicked ${player.Name}` };
			},
		};

		if (RunService.IsStudio()) return;

		task.spawn(() => this.subscribeCommands());
		task.spawn(() => this.subscribeRoster());

		this.event.loop(ANNOUNCE_INTERVAL, () => this.announceSelf());
		this.event.loop(POLL_INTERVAL, () => this.poll());
	}

	private subscribeCommands() {
		for (let attempt = 1; ; attempt++) {
			const [ok, err] = pcall(() =>
				MessagingService.SubscribeAsync(COMMAND_TOPIC, (message) => {
					const raw = (message as { readonly Data: unknown }).Data;
					if (!typeIs(raw, "string")) return;

					const [decodeOk, command] = pcall(() => JSON.deserialize<CommandEnvelope>(raw));
					if (!decodeOk || command === undefined) return;

					this.execute(command);
				}),
			);
			if (ok) {
				this.commandsAlive = true;
				this.announceSelf();
				return;
			}

			warn(`[CommandController] COMMAND SubscribeAsync failed (attempt ${attempt}): ${err}`);
			task.wait(math.min(60, attempt * 5));
		}
	}

	private subscribeRoster() {
		const [ok, err] = pcall(() =>
			MessagingService.SubscribeAsync(ROSTER_TOPIC, (message) => {
				const jobId = (message as { readonly Data: unknown }).Data;
				if (!typeIs(jobId, "string") || jobId === game.JobId) return;

				const isNew = !this.roster.has(jobId);
				this.roster.set(jobId, time());
				if (isNew) this.queueAnnounce();
			}),
		);
		if (!ok)
			warn(`[CommandController] SERVERS SubscribeAsync failed, this server will report an empty roster: ${err}`);
	}

	private announceSelf() {
		if (!this.commandsAlive) return;
		pcall(() => MessagingService.PublishAsync(ROSTER_TOPIC, game.JobId));
	}

	private queueAnnounce() {
		if (this.announceQueued) return;

		this.announceQueued = true;
		task.delay(ANNOUNCE_DEBOUNCE, () => {
			this.announceQueued = false;
			this.announceSelf();
		});
	}

	private liveRoster(): string[] {
		const now = time();
		const alive: string[] = [game.JobId];

		for (const [jobId, lastSeen] of this.roster) {
			if (now - lastSeen > ROSTER_TTL) {
				this.roster.delete(jobId);
				continue;
			}

			alive.push(jobId);
		}

		return alive;
	}

	private execute(command: CommandEnvelope) {
		this.watermark = math.max(this.watermark, command.issuedAt);

		const previous = this.handled.get(command.id);
		if (previous !== undefined) {
			task.spawn(() => this.acknowledge(command.id, previous));
			return;
		}

		const result = this.outcomeFor(command);
		this.remember(command.id, result);
		task.spawn(() => this.acknowledge(command.id, result));
	}

	private outcomeFor(command: CommandEnvelope): CommandResult {
		if (command.targetJobId !== undefined && command.targetJobId !== game.JobId) {
			return { outcome: "Nothing" };
		}

		const handler = this.handlers[command.name];
		if (handler === undefined) return { outcome: "Unsupported" };

		return handler(command.args);
	}

	private remember(id: string, result: CommandResult) {
		this.handled.set(id, result);
		this.handledOrder.push(id);

		while (this.handledOrder.size() > MAX_HANDLED) {
			const oldest = this.handledOrder.remove(0);
			if (oldest !== undefined) this.handled.delete(oldest);
		}
	}

	private acknowledge(id: string, result: CommandResult) {
		const token = getBotToken();
		if (token === undefined) {
			warn("[CommandController] No BOTTOKEN: commands run but are never acknowledged to the bot.");
			return;
		}

		const [ok, err] = pcall(() =>
			HttpService.RequestAsync({
				Url: `${BOT_URL}/ack/${id}`,
				Method: "POST",
				Headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
				Body: JSON.serialize({
					jobId: game.JobId,
					outcome: result.outcome,
					response: result.response,
					kind: serverType(),
					roster: this.liveRoster(),
				}),
			}),
		);
		if (!ok) $warn(`Command acknowledgement failed: ${err}`);
	}

	private poll() {
		const token = getBotToken();
		if (token === undefined) return;

		const [ok, result] = pcall(() =>
			HttpService.RequestAsync({
				Url: `${BOT_URL}/commands?since=${this.watermark}`,
				Method: "GET",
				Headers: { Authorization: `Bearer ${token}` },
			}),
		);
		if (!ok) return;

		const response = result as RequestAsyncResponse;
		if (!response.Success) return;

		const [decodeOk, commands] = pcall(() => JSON.deserialize<CommandEnvelope[]>(response.Body));
		if (!decodeOk || commands === undefined) return;

		for (const command of commands) {
			if (this.seeded) {
				this.execute(command);
				continue;
			}

			this.watermark = math.max(this.watermark, command.issuedAt);
		}

		this.seeded = true;
	}
}
